print('Sofía Álvarez 1160224')
print()
Numero1=int(input("Ingrese un número: "))
kilometro=((Numero1*1)/1000)
Milla=((kilometro*1)/1.69)
Pies=((Numero1*3.28)/1)
pulgadas=((Pies*12)/1)
print("Resultados:")
print("Millas:",Milla)
print("Kilómetros: ",kilometro)
print("Pies: ",Pies)
print("Pulgadas: ",pulgadas)
print()
print("Ejercicio No. 2")
numero=float(input("Ingrese un número: "))
Pies2= int(numero*3.28)
pulgadas= int(Pies2*12)
Yardas= int(Pies2*0.333333)
print("Resultados:")
print("Yardas: ",Yardas)
print("Pies: ",Pies2)
print("Pulgadas: ",pulgadas)